---
# Copyright (C) 2019-2025 PHYTEC
# SPDX-FileCopyrightText: 2025 PHYTEC
#
# SPDX-License-Identifier: MIT
#
# product: PCL-066 / phyCORE-i.MX8M

PHYTEC:
  eeprom_offset: 0x0
  i2c_bus: 0
  i2c_dev: 0x50
  extended_options: 1
  optiontree_rev: 0

Kit:
  0: Processor
  1: Frequency
  2: DDR-Ram
  3: eMMC
  4: NOR-Flash
  5: Ethernet
  6: Wi-Fi
  7: Temperature
  8: Coating
Processor:
  '0': Quad Core Lite (GPU, no VPU)
  '1': Dual Core (GPU, VPU, HDR10)
  '2': Dual Core (GPU, VPU, HDR10, Dolby Vision)
  '3': Quad Core (GPU, VPU, HDR10)
  '4': Quad Core (GPU, VPU, HDR10, Dolby Vision)
Frequency:
  '0': 1.3 GHz
  '1': 1.5 GHz
DDR-Ram:
  '0': 512 MB
  '1': 1 GB
  '2': 1.5 GB
  '3': 2 GB
  '4': 3 GB
  '5': 4 GB
  '6': 6 GB
  '7': 8 GB
eMMC:
  '0': '-'
  '1': 4 GB (MLC)
  '2': 8 GB (MLC)
  '3': 16 GB (MLC)
  '4': 32 GB (MLC)
  '5': 64 GB (MLC)
NOR-Flash:
  '0': '-'
  '1': 4 MB
  '2': 16 MB
  '3': 32 MB
  '4': 64 MB
Ethernet:
  '0': '-  (RGMII on connector)'
  '1': Gbit Ethernet Phy
Wi-Fi:
  '0': '-'
  '1': Wi-Fi/Bluetooth with chip antenna
  '2': Wi-Fi/Bluetooth with U.FL connector
Temperature:
  C: Consumer Temp
  I: Industrial Temp
Coating:
  '0': '-'
  L: Coated
